Repository catchroom/BE_CatchRoom, pull requests merged in 2024-01, with the labels that each got.

#144 Feat : 숙소, 객실 엔티티 도메인 설정
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Room.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationImageRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomImageRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/AccommodationType.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/TransportationType.java
Labels: 🌟 Feat

#146 Feat : OrderHistory, UserTest 작업
  src/main/java/com/example/catchroom_be/domain/product/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/product/repository/OrderHistoryRepository.java
  src/main/java/com/example/catchroom_be/domain/product/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/type/TransportationType.java
  src/main/java/com/example/catchroom_be/domain/test_user/entity/UserTest.java
  src/main/java/com/example/catchroom_be/domain/test_user/repository/UserTestRepository.java
  src/main/java/com/example/catchroom_be/domain/test_user/service/UserTestService.java
Labels: 🌟 Feat

#152 Test/chat 의존성 삭제
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/ChatRoomGetUnique.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/test_user/controller/MemberController.java
  src/main/java/com/example/catchroom_be/domain/test_user/dto/MemberLogInRequest.java
  src/main/java/com/example/catchroom_be/domain/test_user/dto/MemberLogInResponse.java
  src/main/java/com/example/catchroom_be/domain/test_user/dto/MemberSignUpRequest.java
  src/main/java/com/example/catchroom_be/domain/test_user/dto/MemberSignUpResponse.java
  src/main/java/com/example/catchroom_be/domain/test_user/entity/Member.java
  src/main/java/com/example/catchroom_be/domain/test_user/repository/MemberRepository.java
  src/main/java/com/example/catchroom_be/domain/test_user/repository/UserTestRepository.java
  src/main/java/com/example/catchroom_be/domain/test_user/service/MemberService.java
  src/main/java/com/example/catchroom_be/domain/test_user/service/UserTestService.java
  src/main/java/com/example/catchroom_be/global/config/CorsConfig.java
  src/main/java/com/example/catchroom_be/global/config/test_SecurityConfig.java
  src/main/java/com/example/catchroom_be/global/test_security/JwtAuthenticationFilter.java
  src/main/java/com/example/catchroom_be/global/test_security/JwtService.java
  src/main/java/com/example/catchroom_be/global/test_security/MemberDetails.java
  src/main/java/com/example/catchroom_be/global/test_security/MemberDetailsService.java
  src/main/java/com/example/catchroom_be/global/test_security/Role.java
  src/main/java/com/example/catchroom_be/global/test_security/UnauthorizedHandler.java
Labels: ⚒️ Refactor

#154 Refactor : ChatRoom,OrderHistory,Product 도메인에 User 의존성 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/test_user/repository/UserTestRepository.java
  src/main/java/com/example/catchroom_be/domain/test_user/service/UserTestService.java
Labels: ⚒️ Refactor

#155 Feat : Accommodation Controller 작업
  src/main/java/com/example/catchroom_be/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/com/example/catchroom_be/domain/accommodation/exception/AccommodationException.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/service/AccommodationService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🌟 Feat

#156 Deploy : 숙소, 객실 api 배포
  .github/pull_request_template.md
  src/main/java/com/example/catchroom_be/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/com/example/catchroom_be/domain/accommodation/exception/AccommodationException.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/repository/RoomRepository.java
  src/main/java/com/example/catchroom_be/domain/accommodation/service/AccommodationService.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/test_user/repository/UserTestRepository.java
  src/main/java/com/example/catchroom_be/domain/test_user/service/UserTestService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🌎 Deploy

#157 Feat : OrderHistory 도메인 추가
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
Labels: 🌟 Feat

#158 Feat : 판매할 숙박권 상세 조회 로직
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetDetailInfoResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/domain/product/type/DealState.java
Labels: 🌟 Feat

#159 Feature/#32 상품등록
  .gitignore
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🌟 Feat

#162 Feat : 판매 숙박권(상품) 수정 로직 추가
  src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌟 Feat

#166 Feature/#34 상품삭제
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/repository/OrderHistoryRepository.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌟 Feat

#167 Feat : 판매할 숙박권(상품) 등록 시 LocalDate 타입 변경
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
Labels: ⚒️ Refactor

#173 Refactor : 판매 숙박권 리스트 조회/상세조회 인가 임시처리
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/global/config/JwtFilterConfig.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: ⚒️ Refactor

#174 Refactor : 판매 도메인 API 내 회원 인가처리 추가
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
Labels: ⚒️ Refactor

#175 Feature : 회원가입 시 계좌 자동 생성하는 로직 추가
  src/main/java/com/example/catchroom_be/domain/account/entity/Account.java
  src/main/java/com/example/catchroom_be/domain/account/exception/AccountException.java
  src/main/java/com/example/catchroom_be/domain/account/repository/AccountRepository.java
  src/main/java/com/example/catchroom_be/domain/account/service/AccountService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🌟 Feat

#183 Feature/#46 채팅방 내부 정보 조회
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomInfoResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/exception/ChatRoomException.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomInfoService.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/user/controller/user/MeController.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🌟 Feat

#184 Refactor : 채팅방 생성 로직 이전(채팅서버 -> 메인서버)
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomCreateResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomGetUnique.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: ⚒️ Refactor

#189 Feature/#46 채팅방 내부 정보 조회
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: ⚒️ Refactor

#193 수정 부분 배포
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌎 Deploy

#194 fix : spring security config 핫픽스
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🚨 Fix, 🌎 Deploy

#197 Feat : 상품 수정 시 기존 정보 전달 API & 예외처리 완료
  src/main/java/com/example/catchroom_be/domain/product/controller/SaleController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetAllInfoResponse.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetYanoljaReservationResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/exception/ProductException.java
  src/main/java/com/example/catchroom_be/domain/product/exception/SaleException.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeAccessTokenService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeLoginService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
  src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
Labels: 🌟 Feat, ⚒️ Refactor

#200 Feat : 채팅방 리스트 조회 API 개발
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌟 Feat

#201 채팅방리스트 조회 API 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#205 Feat : 채팅방 리스트 반환 시 숙소사진과 채팅상대 닉네임 포함 반환
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: 🌟 Feat

#206 토큰 시간 30분 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
  src/main/java/com/example/catchroom_be/global/jwt/service/MeJWTService.java
Labels: 🌎 Deploy

#207 Feat : Feign API 개발
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🌟 Feat

#210 Feat : 판매숙박권조회 시 매물이름 전달
  src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
Labels: 🌟 Feat

#211 야놀자 매물 리스트 조회 시 매물 이름 추가
  src/main/java/com/example/catchroom_be/domain/orderhistory/dto/OrderHistoryCandidateResponse.java
Labels: 🌎 Deploy

#213 Feat : 채팅방 삭제
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/example/catchroom_be/domain/chatroom/type/ChatRoomState.java
Labels: 🌟 Feat

#214 채팅방 삭제
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/example/catchroom_be/domain/chatroom/type/ChatRoomState.java
Labels: 🌎 Deploy

#217 Feature/#35상품 찜하기
  src/main/java/com/example/catchroom_be/domain/wish/controller/WishController.java
  src/main/java/com/example/catchroom_be/domain/wish/entity/Wish.java
  src/main/java/com/example/catchroom_be/domain/wish/repository/WishRepository.java
  src/main/java/com/example/catchroom_be/domain/wish/service/WishService.java
  src/main/java/com/example/catchroom_be/domain/wish/service/WishServiceImpl.java
Labels: 🌟 Feat

#218 Refact: 엔티티 수정
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/user/entity/User.java
Labels: ⚒️ Refactor

#219 Feature#37상품 구매하기
  src/main/java/com/example/catchroom_be/domain/buyhistory/controller/BuyHistoryController.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/request/BuyRequest.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/request/PaymentRequest.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PaymentResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PurchaseDetailResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/entity/BuyHistory.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/repository/BuyHistoryRepository.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryService.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
Labels: 🌟 Feat

#220 Feature/#29 검색상품조회 1차 완성 (페이징 X)
  src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/AccommodationType.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/AccommodationTypeUtil.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/RegionUtil.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PaymentResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PurchaseDetailResponse.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepository.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductSearchService.java
  src/main/java/com/example/catchroom_be/domain/product/type/ProductSortType.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌟 Feat

#221 상품 검색하기, 구매하기 배포
  src/main/java/com/example/catchroom_be/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/AccommodationType.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/AccommodationTypeUtil.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/RegionUtil.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/controller/BuyHistoryController.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/request/BuyRequest.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/request/PaymentRequest.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PaymentResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PurchaseDetailResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/entity/BuyHistory.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/repository/BuyHistoryRepository.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryService.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepository.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductSearchService.java
  src/main/java/com/example/catchroom_be/domain/product/type/ProductSortType.java
  src/main/java/com/example/catchroom_be/domain/user/entity/User.java
  src/main/java/com/example/catchroom_be/domain/wish/controller/WishController.java
  src/main/java/com/example/catchroom_be/domain/wish/entity/Wish.java
  src/main/java/com/example/catchroom_be/domain/wish/repository/WishRepository.java
  src/main/java/com/example/catchroom_be/domain/wish/service/WishService.java
  src/main/java/com/example/catchroom_be/domain/wish/service/WishServiceImpl.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌎 Deploy

#225 Feature/#29 검색상품조회수정
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductSearchService.java
Labels: 🚨 Fix

#226 Feat : 캐치특가 및 상품종료 날짜 스케줄링 적용
  src/main/java/com/example/catchroom_be/CatchRoomBeApplication.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositAccountNumResponse.java
  src/main/java/com/example/catchroom_be/domain/user/entity/Account.java
  src/main/java/com/example/catchroom_be/domain/user/entity/User.java
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageAccountService.java
Labels: 🌟 Feat

#227 Feature/#26 메인홈에 보여지는 상품 리스트
  src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepository.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌟 Feat

#228 Feat: 메인 홈, 검색 기능 구현
  src/main/java/com/example/catchroom_be/CatchRoomBeApplication.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/entity/OrderHistory.java
  src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepository.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
  src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductSearchService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/domain/user/dto/response/DepositAccountNumResponse.java
  src/main/java/com/example/catchroom_be/domain/user/entity/Account.java
  src/main/java/com/example/catchroom_be/domain/user/entity/User.java
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageAccountService.java
  src/main/java/com/example/catchroom_be/global/config/SecurityConfig.java
Labels: 🌎 Deploy

#229 Fix: 페이지네이션 오류 수정
  src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
Labels: 🚨 Fix

#230 Feat : 캐치특가 및 상품종료 날짜 스케줄링 적용 API 개발
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🌟 Feat

#232 feat : 캐치특가 자동 설정 및 종료날짜 스케줄링 적용
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🚨 Fix, 🌟 Feat, 🌎 Deploy

#233 refactor : 캐치 특가 등록 시 예외처리 개선
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Room.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: ⚒️ Refactor

#234 Refactor : 상품등록 예외처리 리팩토링
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Room.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductController.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🌎 Deploy

#235 HotFix: NullPointException 오류 수정
  src/main/java/com/example/catchroom_be/domain/user/entity/User.java
Labels: 🚨 Fix

#236 refactor : 채팅방 전체 리스트 전달 시 상품 판매 상태 값 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomInfoResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: ⚒️ Refactor

#237 refactor : 채팅방 리스트 전달 시 상품 상태값 포함하여 전달
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomInfoResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: 🌎 Deploy

#240 refactor : 회원가입 시 야놀자 구매 내역 매물 자동 생성
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: ⚒️ Refactor

#241 refactor : 상품 삭제 시 SoftDelete로 변경
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
Labels: ⚒️ Refactor

#242 refactor : 상품 삭제 SoftDelete 적용
  src/main/java/com/example/catchroom_be/domain/orderhistory/controller/OrderHistoryController.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleEditRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/request/SaleRegistRequest.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🌎 Deploy

#245 refactor : 상품 구매 시 예치금 적립 api 개발
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
Labels: 🌟 Feat, ⚒️ Refactor

#248 Fix: 'N+1' 문제 수정
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
Labels: 🚨 Fix

#250 Refactor : 상품 등록 시 판매자 한마디 10글자 제한 로직 제거
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
Labels: 🌎 Deploy

#251 Feature#27리뷰
  src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
  src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
  src/main/java/com/example/catchroom_be/domain/review/dto/response/ReviewSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
Labels: 🌟 Feat

#252 Feat: 리뷰 검색 구현
  src/main/java/com/example/catchroom_be/domain/product/controller/MainController.java
  src/main/java/com/example/catchroom_be/domain/product/service/MainService.java
  src/main/java/com/example/catchroom_be/domain/review/dto/response/ReviewSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/example/catchroom_be/domain/user/service/me/MeRegisterService.java
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageReviewService.java
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageSalesHistoryService.java
Labels: 🌟 Feat

#253 Style :채팅 룸 삭제 log 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🚨 Fix, ✏️ Style

#254 채팅방 삭제 Log 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#255 fix : userID equals 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🚨 Fix

#256 채팅 룸 정렬 방식 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#257 refactor : 숙소 등록 시 id 값 함께 반환
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
Labels: ⚒️ Refactor

#258 Feature/#49 delete chatroom
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
Labels: 🌟 Feat, ⚒️ Refactor

#259 채팅룸 반환시 숙소명 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleRegistResponse.java
Labels: 🌎 Deploy

#262 fix : ChatRoomRepositoryCustomImpl 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
Labels: 🚨 Fix

#263 fix : ChatRoomRepositoryCustomImpl 수 - import 제거
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
Labels: 🚨 Fix

#264 bug fix : 채팅방 query dsl 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
Labels: 🚨 Fix, 🌎 Deploy

#266 refactor : 상품 상세 페이지 조회 시 사진 리스트 조회 로직 개선
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
Labels: 🚨 Fix, ⚒️ Refactor

#267 Refactor : 상품 상세 페이지 조회 개선
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/AccommodationImage.java
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/RoomImage.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
Labels: 🌎 Deploy

#273 Feat : 매일 15시 체크인 지난 매물 DealState 스케줄링
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
  src/main/java/com/example/catchroom_be/domain/product/entity/Product.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
  src/main/java/com/example/catchroom_be/domain/product/type/DealState.java
Labels: 🌎 Deploy

#274 Feat : 매일 15시 체크인 지난 매물 DealState 스케줄링(크론 조건식 수정)
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🚨 Fix

#275 HotFix : 매일 15시 체크인 지난 매물 DealState 스케줄링
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🚨 Fix, 🌎 Deploy

#277 fix : 검색 결과에 region 추가
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductSearchListResponse.java
Labels: 🌟 Feat

#279 Feat : 상품 상세페이지 응답 시 숙소서비스 배열로 응답
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🌟 Feat

#280 Feat : 상품 상세페이지 응답 시 숙소서비스 배열로 응답
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleEditResponse.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductRepository.java
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🌎 Deploy

#282 HotFix : 야놀자 구매 상품이 없을 시 응답 코드 반환 에러 fix
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
Labels: 🚨 Fix

#283 HotFix : 야놀자 구매 상품이 없을 시 응답 코드 반환 에러 fix
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
Labels: 🚨 Fix, 🌎 Deploy

#285 Fix/#28 end date스케줄링수정
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🚨 Fix

#286 HotFix : endDate 체크 주기 변경
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🚨 Fix, 🌎 Deploy

#289 Fix : main 브랜치 복구
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🚨 Fix, 🌎 Deploy

#296 Fix : Price 수정
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetAllInfoResponse.java
Labels: 🚨 Fix

#297 Fix : Price 수정
  src/main/java/com/example/catchroom_be/domain/product/dto/response/SaleGetAllInfoResponse.java
Labels: 🚨 Fix, 🌎 Deploy

#298 feat : 채팅방 내부 정보 api 추가
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌟 Feat

#299 채팅방 내부 정보 api 배포
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#300 fix : api 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🚨 Fix

#301 채팅방 정보 가져오기 api 수정 및 배포
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🚨 Fix, 🌎 Deploy

#305 api 추가 수정 배포
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🌎 Deploy

#306 fix : api info 추가 수정 2
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🚨 Fix

#307 채팅방 내부 정보 불러오기 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🌎 Deploy

#308 fix : api info 추가 수정 3 제발 되라
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🚨 Fix

#309 메인 배포
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#310 fix : info 테스트 api
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
Labels: 🚨 Fix

#313 채팅방 내부 정보 불러오기 api
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#314 fix : 채팅방 내부 정보 불러오기 초기화
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌟 Feat

#315 채팅방 불러오기 마지막 배포 (원상태 복귀)
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#319 Fix : Cron 로그 삭제
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
Labels: 🌎 Deploy

#320 Fix: 이용후기 정렬기준 수정
  README.md
  src/main/java/com/example/catchroom_be/domain/review/dto/response/ReviewSearchListResponse.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryImpl.java
Labels: 🌎 Deploy

#328 배포 : 판매 가능한 상품만 보여지도록 수정
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
Labels: 🌎 Deploy

#330 Fix : 상품 상세페이지 조회 시 찜 클릭 여부 추가
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
Labels: 🚨 Fix

#331 Fix : 상품 상세페이지 조회 시 찜 클릭 여부 추가
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
Labels: 🌎 Deploy

#336 fix : 채팅방에 내 닉네임도 전달되도록 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: 🚨 Fix

#337 채팅방 전송시 내 닉네임도 보이도록 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: 🌎 Deploy

#338 fix : 지역명 충청남도 -> 충북 식으로 수정
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/RegionUtil.java
Labels: 🚨 Fix, ⚒️ Refactor

#339 지역명 수정 후 배포
  src/main/java/com/example/catchroom_be/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/catchroom_be/domain/accommodation/type/RegionUtil.java
Labels: 🌎 Deploy

#340 fix : 채팅방 응답 메시지에 isNego 포함.
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: 🚨 Fix

#341 채팅방 응답시 네고 여부도 같이 넣음
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/response/ChatRoomListGetResponse.java
Labels: 🌎 Deploy

#342 Fix : 상품 등록, 수정 시 에러메세지 세분화
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🚨 Fix

#343 Fix : 상품 등록, 수정 시 에러메세지 세분화
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
  src/main/java/com/example/catchroom_be/global/exception/ErrorCode.java
Labels: 🚨 Fix, 🌎 Deploy

#344 Fix : 체크인날짜가 지난 경우 UNABLESELL enum 추가
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
  src/main/java/com/example/catchroom_be/domain/product/type/DealState.java
Labels: 🚨 Fix, 🌟 Feat, ⚒️ Refactor

#345 Fix : 체크인날짜가 지난 경우 UNABLESELL enum 추가
  src/main/java/com/example/catchroom_be/domain/product/service/SaleSchedulerService.java
  src/main/java/com/example/catchroom_be/domain/product/type/DealState.java
Labels: 🌎 Deploy

#346 fix : 메인홈, 이용후기 정렬 로직 추가 및 수정
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryImpl.java
Labels: 🚨 Fix

#347 Fix : 메인홈, 이용후기 정렬 로직 수정후 배포
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/review/repository/ReviewRepositoryImpl.java
Labels: 🌎 Deploy

#348 Fix : 상품수정 시 DealState 업데이트 코드 정리
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
Labels: 🚨 Fix

#349 Fix : 상품수정 시 DealState 업데이트 코드 정리
  src/main/java/com/example/catchroom_be/domain/product/service/SaleService.java
Labels: 🚨 Fix, 🌎 Deploy

#350 fix : 채팅방 중복 생성 안되게 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🚨 Fix

#351 Fix : 채팅방 중복 생성 안되게 로직을 수정
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: 🚨 Fix, 🌎 Deploy

#352 fix : 구매 가격 - 야놀자 구매 가격에서 수정
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageWishService.java
Labels: 🚨 Fix

#353 Fix : 위시리스트 구매가격 수정
  src/main/java/com/example/catchroom_be/domain/user/service/mypage/MyPageWishService.java
Labels: 🌎 Deploy

#354 fix : 총갯수 유령갯수 수정
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
Labels: 🚨 Fix

#355 Fix : 상품 리스트 조회시 총갯수와 실제 리스트 갯수 동일하게 변경
  README.md
  src/main/java/com/example/catchroom_be/domain/product/controller/ProductSearchController.java
  src/main/java/com/example/catchroom_be/domain/product/repository/MainRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/product/repository/ProductSearchRepositoryImpl.java
Labels: 🌎 Deploy

#356 HotFix: 구매자 닉네임 추가
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PaymentResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/dto/response/PurchaseDetailResponse.java
  src/main/java/com/example/catchroom_be/domain/buyhistory/service/BuyHistoryServiceImpl.java
Labels: 🌎 Deploy
