Repository catchroom/BE_CatchRoom, pull requests merged in 2024-02, with the labels that each got.

#358 Refactor : createChatRoom 시 JPA 활용
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
Labels: ⚒️ Refactor

#359 Update README.md
  README.md
Labels: 📝 Docs

#361 Fix, Deploy : 회원 가입시 주문 내역 자동 생성기 수정
  README.md
  src/main/java/com/example/catchroom_be/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/catchroom_be/domain/chatroom/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/example/catchroom_be/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/example/catchroom_be/domain/chatroom/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/example/catchroom_be/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/example/catchroom_be/domain/orderhistory/service/OrderHistoryService.java
  src/main/java/com/example/catchroom_be/domain/product/dto/response/ProductGetResponse.java
  src/main/java/com/example/catchroom_be/domain/product/service/ProductService.java
Labels: 🌎 Deploy
